### ISSUE TITLE
Can't deal with GitLab

### ISSUE THREAD

**Issue by FransUrbo** [patrickchugh/terravision#42] opened 2023-08-21 07:44 UTC
My repo is `git@gitlab.com:...`, but the code only checks for GitHub.

**Comment by jayor96** [comment] 2023-08-21 19:41
if you replace all "github" with "gitlab" in file modules/gitlibs.py and then change module source definition from "git@gitlab...." to "git::ssh://git@gitlab......" it should work. Also keep in mind that if you use modules from branch via ?ref=... it will not work and you should comment out ?ref part and change default branch in your repo to one which you want to pull.

**Comment by patrickchugh** [comment] 2023-08-21 20:54
thanks for the feedback will work on this fix soon @FransUrbo

**Comment by patrickchugh** [comment] 2023-08-21 21:40
@FransUrbo Can do a `git pull` and try with the latest version?

**Comment by FransUrbo** [comment] 2023-08-22 07:31
@jayor96 I have A LOT of modules! `git@` is a valid source address, so not keen on changing that. Also, using `?ref=` is also a valid source, how else would you be able to have "versioning" of your IaC?

As for latest `main`, I'm getting this error now:
```
Preflight check..
  dot command detected: /opt/homebrew/bin/dot
  gvpr command detected: /opt/homebrew/bin/gvpr
  git command detected: /usr/bin/git
  Added Source Location: /home/turbo/src/module
  Parsing //home/turbo/src/module/state.tf
  Parsing /home/turbo/src/module/main.tf
    Found 1 module stanza(s)
Loading Sources..
  Downloading External Module: git@gitlab.com:my-repository//module?ref=main
    Cloning from Terraform registry source: git@gitlab.com:my-repository//module?ref=main
0it [00:00, ?it/s]
ERROR: Unable to call Git to clone repository! Check git and SSH fingerprints and keys are correct and ensure the URL git@gitlab.com:my-repository//module?ref=main is reachable via CLI.
```

Looking at the code, the `modules/gitlibs.py:clone_files() -> git.Repo.clone_from()` is failing. Not really a Python programmer, so not sure how that's supposed to work..


I just did a `terraform get -update` which worked just fine.


But @jayor96 might be on to something here.. When doing the `get`, I noticed (which I haven't noticed before, strangely! :) ) that TF say:
```
Downloading git::ssh://git@gitlab.com/my-repository?ref=main for my-module...
```

So I wonder if TF is "prefixing" a `git@...` source (which is a valid GIT source) with `git::ssh://` and maybe that's why TV isn't working?

**Comment by jayor96** [comment] 2023-08-22 08:15
The problem is that terravision got its own logic to fetch modules which is different than in terraform and it can't work with branches and normal git syntax. I was just experimenting with one of my smaller infra projects to get some output to see if its working but even after I fix all git related issues I get into problems with python itself and how it declare variables internally

**Comment by patrickchugh** [comment] 2023-08-22 21:01
@FransUrbo @jayor96 can you provide me some sample Terraform to try to reproduce your problem?  This should not be difficult to fix.

**Comment by patrickchugh** [comment] 2023-08-26 10:49
@FransUrbo Please git pull the latest code and try again. I am able to use gitlab with both ssh and https. 

 terravision draw --source git@gitlab.com:patrickchugh/test.git --show --debug 

Preflight check..
  dot command detected: /usr/local/bin/dot
  gvpr command detected: /usr/local/bin/gvpr
  git command detected: /usr/local/bin/git
Loading Sources..
  Downloading External Module: git@gitlab.com:patrickchugh/test.git
    Cloning from Terraform registry source: git@gitlab.com:patrickchugh/test.git
  Added Source Location: git@gitlab.com:patrickchugh/test.git                                       
  Parsing /Users/patrick/.terravision/module_cache/git@gitlab.com_patrickchugh/test.git;main;/main.tf
    Found 5 resource stanza(s)
  Parsing /Users/patrick/.terravision/module_cache/git@gitlab.com_patrickchugh/test.git;main;/network.tf
    Found 2 resource stanza(s)
  Parsing /Users/patrick/.terravision/module_cache/git@gitlab.com_patrickchugh/test.git;main;/sg.tf
    Found 1 resource stanza(s)
.....

Final Graphviz Input Dictionary
{
    "aws_az.az": [
        "aws_subnet.mysubnet"
    ],
    "aws_cloudwatch_log_group.cloudwatch": [],
    "aws_group.shared_services": [
        "aws_cloudwatch_log_group.cloudwatch"
    ],
    "aws_iam_policy.policy": [],
    "aws_iam_policy_attachment.test-attach": [
        "aws_iam_policy.policy"
    ],
    "aws_iam_role.another_role": [],
    "aws_iam_role.iam_for_lambda": [
        "aws_iam_policy_attachment.test-attach",
        "aws_lambda_function.test_lambda"
    ],
    "aws_lambda_function.test_lambda": [
        "aws_cloudwatch_log_group.cloudwatch"
    ],
    "aws_security_group.allow_tls": [
        "aws_lambda_function.test_lambda"
    ],
    "aws_subnet.mysubnet": [
        "aws_security_group.allow_tls"
    ],
    "aws_vpc.main": [
        "aws_az.az"
    ]
}

Rendering Architecture Image...
  Output file: /Users/patrick/git/terravision/architecture.dot.png
  Completed!

**Comment by patrickchugh** [comment] 2023-08-26 11:45
@jayor96  Can you try again with the latest fixes I made ? git pull the main branch

**Comment by jayor96** [comment] 2023-08-28 07:46
@patrickchugh Hello, pull of code works now thanks. But I still hit this error 
Unhandled error: <class 'TypeError'>, argument of type 'int' is not iterable, <traceback object at 0x106ad5c40>
Should I open issue with it ? I'm afraid that without some debug mode I can't provide variable which is causing issue as my infra is large and complex

**Comment by patrickchugh** [comment] 2023-08-28 07:49
@jayor96 I will be updating the code to produce more meaningful debug you can try again then

**Comment by jayor96** [comment] 2023-08-28 07:52
@patrickchugh Great ! Thanks for info

**Comment by patrickchugh** [comment] 2023-08-28 11:19
@jayor96  I made some changes to the code now to show more verbose debug messages you can paste the relevant lines from the output if necessary. Let me know if it works?

**Comment by jayor96** [comment] 2023-08-28 11:32
@patrickchugh I can't give you full outcome as it contains sensitive data, but here is cleared error which i get

ERROR: LB : aws_lb_target_group.main count = 0 (Error in calling function True  ? ERROR!_length([ 'something': 'likethis', random:5, .....  ]) : 0))
Unhandled error: <class 'TypeError'>, argument of type 'int' is not iterable, <traceback object at 0x1061a3d40>

**Comment by patrickchugh** [comment] 2023-12-20 23:04
This is fixed with the latest code @jayor96

**Closed by patrickchugh** 2023-12-20 23:04 UTC
