### ISSUE TITLE
Most of the repo failing with error

### ISSUE THREAD

**Issue by surajtikoo** [patrickchugh/terravision#69] opened 2023-10-31 09:16 UTC
Unhandled error: <class 'RecursionError'>, maximum recursion depth exceeded while calling a Python object, <traceback object at 0x104bf1840>
tried with sample open source repo
https://github.com/geekcell/terraform-aws-ecs-fargate-alb.git

**Comment by patrickchugh** [comment] 2023-11-21 00:24
@surajtikoo Hello, thank you for your feedback and thanks for testing out Terravision and helping to make this a better product. I have recently completed a major revamp to the code which uses the terraform binary to download source files and generate initial relationships, before augmenting it with source code parsing as before. This is a significant departure from the previous approach and whilst slower, ensures a more accurate output and  will handle all terraform in built functions now when encountered in the source.  Please do a git pull and re-test again with the latest source code. If your problem is resolved, please close the the thread in github issues and mark it as completed. If not, please give as much detail as you can about the errors and include any source files if possible so I can reproduce your issue. Once again, thanks for helping and look forward to hearing from you soon.

P.

**Comment by patrickchugh** [comment] 2023-12-20 23:05
@surajtikoo closing since no feedback received

**Closed by patrickchugh** 2023-12-20 23:05 UTC
